### ISSUE TITLE
Login dan Register design

### ISSUE THREAD

**Issue by ghost** [Programmer-Muda/chatkuy#2]
@kamalbacrur kapan bisa mulai? kalau perlu w bikin salah satu designnya buat bantu" 😄 

- [ ] Design Halaman Register
- [ ] Design Halaman Login

**Comment by kamalbacrur** [comment]
Tunggu gan....gua lagi banyak tugas remedial dan test, mungkin Minggu depan
gan

Pada tanggal Min, 16 Jun 2019 15.24, Ahmad Reza <notifications@github.com>
menulis:

**Comment by ghost** [comment]
Oke gan sementara w aja yang ngerjain

**Comment by ghost** [comment]
Dikarenakan kita pakai firebase jadi ga usah repot bikin :v
